name: Debug - create txt file and deploy to GitHub Pages

on:
  # push:
  #   branches:
  #     - master  # Run the workflow on pushes to the main branch
  workflow_dispatch:  # Run the workflow on manual trigger

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: List files in the repository
      - name: List Files
        run: ls -la

      # Step 2: Print the working directory
      - name: pwd
        run: pwd > file.txt

      # Step 3: Upload the file.txt artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: file-txt
          path: .

  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: file-txt
      
  